version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  droidian-buildd: who53/droidian-buildd-orb@dev:alpha

jobs:
  setup:
    executor: continuation/default
    resource_class: small
    steps:
      - droidian-buildd/checkout
      - droidian-buildd/generate
      - continuation/continue:
          configuration_path: generated_config.yml

workflows:
  setup:
    jobs:
      - setup:
          filters:
            tags:
              only: /^droidian\/.*\/.*/
